[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  query = {p = ":path"} # apply this rule for /?p=example  
  # force = false
  # hash = ":path" # does hash work, or do we need to use the query string?
