[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  query = {page = ":path"} # apply this rule for /?page=example  
  # force = false
  # hash = ":path" # does hash work, or do we need to use the query string?
