[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = false
  hash = ":path" # does hash work, or do we need to use the query string?
  # query = {path = ":path"} # apply this rule for /?path=example